CREATE TABLE "events" (
	"pool_id" text NOT NULL,
	"event_id" text NOT NULL,
	"recipient" text NOT NULL,
	"sender" text NOT NULL,
	"ts" text NOT NULL,
	"scope_id" text,
	"kudos" bigint DEFAULT 1 NOT NULL,
	"emoji" text,
	"title" text,
	"visibility" text DEFAULT 'PRIVATE' NOT NULL,
	"meta" text,
	"inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "events_pool_id_event_id_pk" PRIMARY KEY("pool_id","event_id")
);
--> statement-breakpoint
CREATE TABLE "outbox" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "outbox_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pool_id" text NOT NULL,
	"event_id" text NOT NULL,
	"payload" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"delivered" integer DEFAULT 0 NOT NULL,
	"delivered_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"leased_at" timestamp with time zone,
	"lease_id" text
);
--> statement-breakpoint
CREATE TABLE "pool_recipient_totals" (
	"pool_id" text NOT NULL,
	"recipient" text NOT NULL,
	"kudos" bigint DEFAULT 0 NOT NULL,
	"emojis" text DEFAULT '[]' NOT NULL,
	CONSTRAINT "pool_recipient_totals_pool_id_recipient_pk" PRIMARY KEY("pool_id","recipient")
);
--> statement-breakpoint
CREATE TABLE "pool_scope_latest" (
	"pool_id" text NOT NULL,
	"recipient" text NOT NULL,
	"scope_id" text NOT NULL,
	"event_id" text NOT NULL,
	"kudos" bigint NOT NULL,
	"ts" text NOT NULL,
	CONSTRAINT "pool_scope_latest_pool_id_recipient_scope_id_pk" PRIMARY KEY("pool_id","recipient","scope_id")
);
--> statement-breakpoint
CREATE TABLE "pool_totals" (
	"pool_id" text PRIMARY KEY NOT NULL,
	"kudos" bigint DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_events_pool_ts_id" ON "events" USING btree ("pool_id","ts","event_id");--> statement-breakpoint
CREATE INDEX "idx_outbox_pending" ON "outbox" USING btree ("delivered","created_at");--> statement-breakpoint
CREATE INDEX "idx_recipient_totals_by_kudos" ON "pool_recipient_totals" USING btree ("pool_id","kudos");