name: Kudos
on:
  push:
    branches: [$default-branch]

jobs:
  kudos:
    name: Find contributors and Ink Kudos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm i
      - uses: LoremLabs/kudos-for-code-action@main
        with:
          search-dir: "."
          dev-dependencies: "false"
